<?php
/** @var \Magento\Framework\View\TemplateEngineInterface $this */
/** @var \Magebit\PageListWidget\Block\Widget\PageList $block */
/** @var \Magento\Csp\Api\InlineUtilInterface $csp */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<h3><?php echo($block->getTitle())?></h3>

<h3><?php $pages = $block->getChosenPages()?></h3>

<ul>
    <?php foreach ($pages as $page): ?>
        <li><a href="<?php echo $block->getHref($page->getId()); ?>"><?php echo $page->getTitle(); ?></a></li>
    <?php endforeach; ?>
</ul>


