<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Theme\Block\Html\Breadcrumbs;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Breadcrumbs $block */
/** @var array[] $crumbs */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroicons */
$heroicons = $viewModels->require(HeroiconsSolid::class);

?>
<?php if ($crumbs && is_array($crumbs)): ?>
<nav class="breadcrumbs bg-container-lighter shadow-sm" aria-label="Breadcrumb">
    <div class="container">
        <ol class="items list-reset py-4 rounded flex flex-wrap text-grey text-sm">
            <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
                <li class="item flex <?= $escaper->escapeHtmlAttr($crumbName) ?>">
                <?php if (!$crumbInfo['first']): ?>
                    <span aria-hidden="true" class="separator px-2 mt-0.5">
                        <?= $heroicons->chevronRightHtml('text-gray-500', 16, 16, ['aria-hidden' => 'true']) ?>
                    </span>
                <?php endif; ?>
                <?php if ($crumbInfo['link']): ?>
                    <a href="<?= $escaper->escapeUrl($crumbInfo['link']) ?>"
                       class="no-underline"
                       title="<?= $escaper->escapeHtmlAttr($crumbInfo['title']) ?>"
                    ><?= $escaper->escapeHtml($crumbInfo['label']) ?></a>
                <?php elseif ($crumbInfo['last']): ?>
                    <span
                       class="text-primary-lighter"
                       aria-current="page"
                    ><?= $escaper->escapeHtml($crumbInfo['label']) ?></span>
                <?php else: ?>
                    <?= $escaper->escapeHtml($crumbInfo['label']) ?>
                <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
</nav>
<?php endif; ?>
