<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;

/** @var ViewModelRegistry $viewModels */
?>

<div class="example">
    <div x-data="cmsBlock()" x-init="init">
        <div x-html="block.title"></div>
        <div x-html="block.content"></div>
    </div>
</div>

<script>
    function cmsBlock() {
        return {
            block: {
                title: '',
                content: '',
                identifier: ''
            },
            init : function() {
                const url = BASE_URL + 'graphql';
                fetch(url, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({query: `{
                        cmsBlocks(identifiers:["home-page-block"]) {
                            items {
                                content
                                identifier
                                title
                            }
                        }
                    }`
                    })
                })
                    .then(response => response.json())
                    .then(responseJson => {
                        this.block.title = responseJson.data.cmsBlocks.items[0].title
                        this.block.identifier = responseJson.data.cmsBlocks.items[0].identifier
                        this.block.content = responseJson.data.cmsBlocks.items[0].content
                    })
            }
        }
    }
</script>


