<?php
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/** @var Magento\Catalog\Block\Product\View $block */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty" id="qty-component">
                    <div class="control" data-bind="scope: 'qty-counter'">
                        <div class="qty-control">
                            <button class="qty-decrease qty-button" data-bind="click: decreaseQty">-</button>
                            <input data-bind="value: qty()"
                                   type="number"
                                   name="qty"
                                   id="qty"
                                   maxlength="10"
                                   title="<?php echo __('Qty') ?>"
                                   class="input-text qty"
                                   data-validate="<?php echo json_encode($block->getQuantityValidators()) ?>"
                            />

                            <button class="qty-increase qty-button" data-bind="click: increaseQty">+</button>
                        </div>

                    </div>
                </div>

                <script type="text/x-magento-init">
                    {
                        "#qty-component":{
                            "Magento_Ui/js/core/app":{
                                "components":{
                                    "qty-counter":{
                                        "component": "Magento_Catalog/js/qty_counter",
                                        "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                                    }
                                }
                            }
                        }
                    }
                </script>

            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
            }
        }
    </script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
            }
        }
    </script>
<?php endif; ?>
