<?php
/** @var Magento\Catalog\Block\Product\View\Description $block */

//$product = $block->getShort();
//
//$description = $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getCurrentCategory()->getShortDescription(), 'description')
//?>
<!---->
<?php //= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute(
//    $block->getProduct(),
//    $block->getProduct()->getDescription(),
//    'description'
//) ?>

